# Generated by Django 4.0.2 on 2022-03-07 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CattleSex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_contact', models.IntegerField(default='0700368906')),
                ('breed', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('selling_price_range', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('cattle_age', models.IntegerField()),
                ('health_record_book', models.FileField(upload_to='cattle/health_record/')),
                ('cattle_picture', models.ImageField(upload_to='cattle/cattle_pictures/')),
                ('cattle_sex_based_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.cattlesex')),
            ],
        ),
    ]
