# Generated by Django 4.0.2 on 2022-03-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='owner_contact',
            field=models.IntegerField(),
        ),
    ]
