# Generated by Django 4.0.2 on 2022-03-12 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0003_alter_cattle_owner_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_types', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ToolPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools_purpose', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_contact', models.IntegerField()),
                ('tool_name', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('brief_its_usage', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('tools_number', models.IntegerField()),
                ('maximum_selling_price', models.IntegerField()),
                ('animals_type', models.CharField(blank=True, max_length=500, null=True)),
                ('machinery_tool_picture', models.ImageField(upload_to='machinery/machinery_tools_pictures/')),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.animaltype')),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tool_purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.toolpurpose')),
            ],
        ),
    ]
