# Generated by Django 4.0.2 on 2022-03-12 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0004_animaltype_toolpurpose_machinery'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoatSex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goat_sex', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Goat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_contact', models.IntegerField()),
                ('breed', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('maximum_selling_price', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('goat_age', models.IntegerField()),
                ('health_record_book', models.FileField(upload_to='goat/health_record/')),
                ('goat_picture', models.ImageField(upload_to='goat/goat_pictures/')),
                ('goat_sex_based_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.goatsex')),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
